# Generated by Django 2.0.3 on 2021-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('emp_id', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('number', models.BigIntegerField()),
                ('position', models.CharField(max_length=30)),
                ('typeofwork', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
