# Generated by Django 2.0.3 on 2021-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210226_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='number',
            field=models.BigIntegerField(default=10),
        ),
    ]
