# Generated by Django 2.0.3 on 2021-03-07 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210307_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='number',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)]),
        ),
    ]
