# Generated by Django 2.0.3 on 2021-03-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210307_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
