# Generated by Django 2.0.3 on 2021-03-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210307_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
