# Generated by Django 2.0.3 on 2021-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employees_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
