# Generated by Django 2.0.3 on 2021-03-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210315_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
