# Generated by Django 2.0.3 on 2021-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210315_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='resume',
        ),
        migrations.AddField(
            model_name='employees',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
