# Generated by Django 2.0.3 on 2021-03-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210315_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
